# Generated by Django 2.1.2 on 2018-10-14 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='screen',
            fields=[
                ('screenId', models.AutoField(primary_key=True, serialize=False)),
                ('screenName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowName', models.CharField(max_length=1)),
                ('seatNo', models.IntegerField()),
                ('status', models.SmallIntegerField(default=0)),
                ('isAisle', models.SmallIntegerField(default=0)),
                ('screenId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.screen')),
            ],
        ),
    ]
